language: node_js

node_js:
  - node

script: yarn build

deploy:
  # GitHub Pages
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: demo
    skip-cleanup: true
    on:
      branch: master
  # GitHub Releases
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: dist/font-picker/font-picker/FontPicker.js
    skip_cleanup: true
    on:
      tags: true
